migrate to yarn from npm #102
sugarlabs/musicblocks-v4-lib pull request #105
Opened 2022-01-21 16:16 UTC by Gri-ffin

2022-01-21 16:27 UTC, meganindya requested changes
Please see the comments. Other than that it's better to classify README changes as `docs` commits and project setup changes as `chore`. So, your first commit is a `chore` while the last two are `docs`. In fact, you can squash down your last two commits into one. An interactive rebase will get these done.

2022-01-21 16:27 UTC, meganindya commented on .github/workflows/CI.yml
> +      # - run: yarn run build --if-present
remove this

2022-01-21 16:27 UTC, meganindya commented on README.md
> +    _**Node**_ (_Node.js Runtime_), _**yarn**_ (_Node Package Manager_), _**tsc**_ (_TypeScript
*Yarn Package Manager

2022-01-21 16:29 UTC, Gri-ffin commented on .github/workflows/CI.yml
> +      # - run: yarn run build --if-present
do you mean the comment?

2022-01-21 16:35 UTC, meganindya commented on .github/workflows/CI.yml
> +      # - run: yarn run build --if-present
yes

2022-01-21 17:08 UTC, meganindya approved these changes

2022-01-22 12:11 UTC, meganindya commented
Can you fix the merge conflicts and rebase your branch? I want to run the workflows before merging PRs (even though this PR shouldn't really have linting issues). There was something broken with the Super Linter which has been fixed now.

2022-01-22 17:48 UTC, closed without merging