Specification: Add validation in functions
sugarlabs/musicblocks-v4-lib pull request #117
Opened 2022-01-27 11:43 UTC by ColabAkshat

#112 

Added validations as mentioned in issue #112.

2022-01-27 13:33 UTC, meganindya requested changes
Please make the changes. I am a little protective of what goes into this repo.

Also, split the two comments; one for the function changes and one for the tests. Add description in the commits as to what changed.

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> + * @returns false if element name already exists, else true
\`false\` if element name already exists else \`true\`

add the backticks; slight quirk

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> + * @returns a list of boolean , false if element name already exists else true
a list of boolean values, \`false\` if element name already exists else \`true\`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> +        return !(name in _elementSpecification);
`return true` will do

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> +        return true;
`return false` if element entry doesn't exist already

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> + * @returns true if element is successfully removed, else false
\`true\` if element entry is successfully removed else \`false\`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> + * @returns a list of boolean, true if element is successfully removed, else false
a list of boolean values, \`true\` if element is successfully removed else \`false\`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> +    return registerElementsEntries;
use variable name `registerStatus` instead of `registerElementsEntries`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.ts
> +    return successfullyRemoved;
use variable name `removeStatus` instead of `successfullyRemoved`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            const registerElement = registerElementSpecificationEntry('dummy0', {
`const status`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +
remove newline

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            expect(registerElement).toBeTruthy();
`expect(...).toBe(true)`

I prefer strict checks

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            expect(registerElementAgain).toBeFalsy();
`.toBe(false)`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            const elementRemoved = removeElementSpecificationEntry('dummy0' as TElementName);
`const status`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +
remove newline

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            expect(elementRemoved).toBeTruthy();
`expect(status).toBe(true);`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            expect(registerElementAgain).toBeFalsy();
put this in a separate test
`register duplicate element specification entry and verify`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
>          test('register element specification entry and verify', () => {
`register new element specification entry and verify`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            const registerElementEntries = registerElementSpecificationEntries({
`const status1`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            const registerElementEntriesAgain = registerElementSpecificationEntries({
```ts
// attempt to register some new and duplicated entries
const status2 = ...
```

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
>          test('remove element specification entry and verify', () => {
`remove valid element specification entry and verify`

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
>          });
add a test for removing an invalid entry

2022-01-27 13:33 UTC, meganindya commented on src/syntax/specification/specification.spec.ts
> +            ]);
also add a `false` case

2022-01-27 17:17 UTC, closed without merging

2022-01-28 11:22 UTC, ColabAkshat commented
Made the necessary changes in #118, please review it once.