test case added
sugarlabs/musicblocks-v4-lib pull request #37
Opened 2021-03-27 01:35 UTC by joykirat18

Issue Reference: #25

This PR adds test cases for temperament.ts. The code coverage is above 80% in temperament.
Also, there is a minor change in the if-else statement of temperament.ts. `!(noteName in this._genericNoteNames)` at line 431 in was always returning true to I have to change it into `!this._genericNoteNames.includes(noteName)`. 

<img width="689" alt="Screenshot 2021-03-27 at 6 24 04 AM" src="https://user-images.githubusercontent.com/66181127/112705694-f2e92800-8ec5-11eb-826c-2457eaee8fac.png">
<img width="1108" alt="Screenshot 2021-03-27 at 6 23 08 AM" src="https://user-images.githubusercontent.com/66181127/112705726-098f7f00-8ec6-11eb-81f3-08557b3a844f.png">
All test cases are passed.
Please review the code @meganindya 
Thanks.

2021-03-27 12:55 UTC, meganindya commented
Is this exhaustive?

2021-03-27 12:55 UTC, meganindya commented
BTW, please stick to all of these &mdash; https://github.com/sugarlabs/musicblocks-v4-lib#code-quality-notes

2021-03-27 13:56 UTC, joykirat18 commented
Some of the functions are remaining I will soon add the remaining test cases.

2021-03-27 14:00 UTC, joykirat18 commented
I have added the test cases please have a look @meganindya .
Thanks

2021-03-29 11:22 UTC, meganindya requested changes
There have been incoming changes made to `Temperament`. Two cases fail. Please verify them.

2021-03-30 11:41 UTC, meganindya approved these changes
Fixed it.

![Screenshot 2021-03-30 at 5 10 37 PM](https://user-images.githubusercontent.com/33328728/112983116-e5a89380-917a-11eb-8b5c-55aa76c786ae.png)

2021-03-30 11:41 UTC, merged